### ISSUE TITLE
Building using the WATCOM compiler fails

### ISSUE THREAD

**Issue by renodr** [c-ares/c-ares#622]
When trying to build c-ares-1.22.0 under OpenWatcom, I get hit with:
```
        wcc386 -3r -mf -hc -zff -zgf -zq -zm -zc -s -fr=con -w2 -fpi -oilrtfm -aa -wcd=201 -bt=nt -d+ -dWIN32 
-dCARES_BUILDING_LIBRARY -dNTDDI_VERSION=0x06000000 -I. -I.\include -I.\src\lib -IC:\WATCOM\h\nt -IC:\WATCOM\h -d0 
-d_WIN32_WINNT=0x0602 -bd .\src\lib\ares__buf -fo=WC_Win32.obj\dyn\ares__buf.obj
.\src\lib\ares__buf.c(96): Error! E1011: Symbol 'SIZE_MAX' has not been declared
.\src\lib\ares__buf.c(160): Error! E1011: Symbol 'SIZE_MAX' has not been declared
.\src\lib\ares__buf.c(403): Error! E1011: Symbol 'SIZE_MAX' has not been declared
.\src\lib\ares__buf.c(414): Error! E1011: Symbol 'SIZE_MAX' has not been declared
.\src\lib\ares__buf.c(424): Error! E1011: Symbol 'SIZE_MAX' has not been declared
.\src\lib\ares__buf.c(434): Error! E1011: Symbol 'SIZE_MAX' has not been declared
Error(E42): Last command making (WC_Win32.obj\dyn\ares__buf.obj) returned a bad status
Error(E02): Make execution terminated
```

SIZE_MAX should come from stdint.h. On a system that uses configure or CMake, HAVE_STDINT_H would be defined so that stdint.h would be included (and it makes sense to guard around it in code as well).

I'm not sure why this hasn't broken before, but 1.21.0 built fine. I'm going to start building Git master a bit more often and would like to look into contributing a CI workflow for Watcom in the future since OpenWatcom is available in CI now. 😃 

To work around this I've added -dHAVE_STDINT_H to the CFLAGS within Makefile.Watcom and it built fine for me that way, so I'll submit that as a PR shortly! I've tested it with adig and ahost and they both work well. 😃

**Comment by bradh352** [comment]
It'd be great to have info on how to build this for CI/CD.

**Comment by bradh352** [comment]
Wonder if we could essentially use this for our CI/CD with minor tweaks: https://github.com/libsdl-org/sdl12-compat/blob/main/.github/workflows/watcom.yml

**Comment by renodr** [comment]
> Wonder if we could essentially use this for our CI/CD with minor tweaks: https://github.com/libsdl-org/sdl12-compat/blob/main/.github/workflows/watcom.yml

We should definitely be able to! To build it, we'd need to use 'wmake -u -f Makefile.Watcom'

Something like this maybe:
```

name: Build (OpenWatcom)

on: [push, pull_request]

jobs:
  Win32:
    runs-on: windows-latest

    steps:
      - uses: open-watcom/setup-watcom@v0
      - name: Get c-ares sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build c-ares
        run: |
          wmake -u -f Makefile.Watcom
      - name: distclean
        run: |
          wmake -u -f Makefile.Watcom clean
```

I haven't tested this though
